name: Update recent activity

on:
  schedule:
    - cron: "15 */6 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/recent-activity.yml"
      - ".github/recent-activity.config.yml"

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update recent activity
        uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          CONFIG_FILE: ./.github/recent-activity.config.yml
